### ISSUE TITLE
demo_multitaper中pmtm的使用是否有误

### ISSUE THREAD

**Issue by KingNoth1ng** [zhangzg78/eegbook#1]
老师你好，在demo_multitaper中，pmtm函数的使用是否存在问题？
如
`[P_mtm_1, f] = pmtm(x,4,nfft,Fs)`
书中是将参数 4 解释为锥形窗数目，但是在matlab pmtm函数的说明文件中：

[pxx,f] = pmtm(___,fs) returns a frequency vector, f, in cycles per unit time. fs must follow x, nw **(or m for sine tapers)**, and nfft in the function call. To input a sample rate and still use the default values of the preceding arguments, specify these arguments as empty, [].

在设置tapers为sin时这个参数才为窗数目，而默认的taper是Slepian，在不更改tapers类型时这个参数应该表示的为mw吧？

**Comment by zhangzg78** [comment]
不好意思，刚看到邮件，回复晚了些。
这里或许有些误解：

  1.  nw在Matlab的帮助文件里写得很清楚，time-halfbandwidth product。而你引用的是说sine tapers时的参数为m。你可以看help文件的其他部分说明。
  2.  我的书里文字没有写nw是窗口，我的原话是“在“pmtm.m”中，我们需要指定一个半时带宽乘积nw，它决定了多窗口频谱估计的频率分辨率。因为在“pmtm.m”中使用的锥形窗数目是L=(2nwC1)……“
如果你还有疑问请随时联系我。

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________
From: KingNoth1ng ***@***.***>
Sent: Sunday, December 18, 2022 11:54:38 AM
To: zhangzg78/eegbook ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zhangzg78/eegbook] demo_welch中pmtm的使用是否有误 (Issue #1)


老师你好，在demo_multitaper中，pmtm函数的使用是否存在问题？
如
[P_mtm_1, f] = pmtm(x,4,nfft,Fs)
书中是将参数 4 解释为锥形窗数目，但是在matlab pmtm函数的说明文件中：
[pxx,f] = pmtm(___,fs) returns a frequency vector, f, in cycles per unit time. fs must follow x, nw **(or m for sine tapers)**, and nfft in the function call. To input a sample rate and still use the default values of the preceding arguments, specify these arguments as empty, [].

在设置tapers为sin时这个参数才为窗数目，而默认的taper是Slepian，在不更改tapers类型时这个参数应该表示的为mw吧？

―

**Comment by KingNoth1ng** [comment]
谢谢老师解答，是我表述错误。书中的文字内容是没问题的，我疑惑的地方是代码和图例上面
![image](https://user-images.githubusercontent.com/117706788/208923921-eacd354d-cbdf-44a6-a39b-3d1adc1d9d27.png)
在图5.5中，图(b)的注释里标注的是L=4  L=2  L=6
而代码：
`[P_mtm_1, f] = pmtm(x,4,nfft,Fs);
[P_mtm_2, f] = pmtm(x,2,nfft,Fs);
[P_mtm_3, f] = pmtm(x,6,nfft,Fs);`

输入的参数也分别是 4 ，2  ，6
如果这里指定的是半时带宽乘积nw，那么按照L=（2nw-1)，图例的L不应该为7  ，  3  ，  11才对吗？
如果这里指定的是窗口数L，那么可以和图例对应上，但是好像在matlab中pmtm需要设置成sine tapers后这个参数的位置才能是窗口数
这是我困惑的地方，是否是图例存在错误？还是我哪里存在误解，烦请批评指正

**Comment by zhangzg78** [comment]
抱歉，图例有错误。我找机会修改。


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
